name: order_test
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  # Nếu muốn xử lý đường dẫn file hoặc ghi file JSON sau này
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
